apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kex.name" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "kex.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "kex.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "kex.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "kex.name" . }}
      containers:
        - name: kex
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
          env:
            - name: ARGOCD_SERVER
              value: {{ .Values.argocdServer | quote }}
            {{- if .Values.argocdTokenSecretName }}
            - name: ARGOCD_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.argocdTokenSecretName }}
                  key: {{ .Values.argocdTokenSecretKey }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
          resources: {{- toYaml .Values.resources | nindent 12 }}
