apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kex.name" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "kex.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kex.name" . }}-reader
  labels: {{- include "kex.labels" . | nindent 4 }}
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["applications"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["traefik.io"]
    resources: ["ingressroutes"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kex.name" . }}-reader
  labels: {{- include "kex.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kex.name" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "kex.name" . }}-reader
  apiGroup: rbac.authorization.k8s.io
